model:
  class_path: pyad.lightning.one_class.LitDeepSVDD
  init_args:
    feature_dim: 512
    hidden_dims:
      - 128
      - 256
    activation: relu
    eps: 0.1
    weight_decay: 1e-6
    lr: 1e-4