model:
  class_path: pyad.lightning.reconstruction.LitMemAE
  init_args:
    mem_dim: 150
    latent_dim: 10
    enc_hidden_dims:
      - 40
      - 20
    shrink_thresh: 0.0025
    alpha: 2e-4
    activation: relu
    weight_decay: 1e-4
    lr: 1e-4