model:
  class_path: pyad.lightning.transformers.LitGOAD
  init_args:
    lr: 1e-3
    n_transforms: 64
    feature_dim: 64
    num_hidden_nodes: 32
    batch_size: 64
    n_layers: 5
    eps: 0
    lamb: 0.1
    margin: 1
trainer:
  max_epochs: 25
data:
  init_args:
    batch_size: 64