model:
  class_path: pyad.lightning.adversarial.LitALAD
  init_args:
    weight_decay: 1e-6
    lr: 1e-5
    latent_dim: 64
    out_dim: 128
    negative_slope: 0.2
data:
  init_args:
    batch_size: 32