model:
  class_path: pyad.lightning.transformers.LitGOAD
  init_args:
    weight_decay: 1e-4
    lr: 1e-4
    n_transforms: 256
    feature_dim: 32
    num_hidden_nodes: 8
    batch_size: 128
    n_layers: 0
    eps: 0
    lamb: 0.1
    margin: 1