model:
  class_path: pyad.lightning.reconstruction.LitAutoEncoder
  init_args:
<<<<<<< HEAD
    hidden_dims:
      - 32
    latent_dim: 2
    reg: 0.5
    activation: relu
    weight_decay: 1e-6
=======
    latent_dim: 10
    hidden_dims:
      - 40
      - 20
    activation: relu
    reg: 0.5
    weight_decay: 1e-4
>>>>>>> f4c0b75fa21d0b150fb909451e8f6b57f11ff51c
    lr: 1e-4