model:
  class_path: pyad.lightning.adversarial.LitALAD
  init_args:
    weight_decay: 1e-4
    lr: 1e-4
    latent_dim: 32
    out_dim: 128
    negative_slope: 0.2
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 200
data:
  class_path: pyad.datamanager.datamodule.ThyroidDataModule
  init_args:
    batch_size: 1024
    data_dir: ./data/Thyroid/thyroid.mat
    scaler: standard
