model:
  class_path: pyad.lightning.density.LitDAGMM
  init_args:
    n_mixtures: 2
    gmm_hidden_dims:
    - 10
    latent_dim: 1
    ae_hidden_dims:
    - 12
    - 4
    dropout_rate: 0.5
    ae_activation: tanh
    gmm_activation: tanh
    lamb_1: 0.1
    lamb_2: 0.005
    reg_covar: 1e-12
    weight_decay: 1e-4
    lr: 1e-4
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 200
data:
  class_path: pyad.datamanager.datamodule.ThyroidDataModule
  init_args:
    batch_size: 1024
    data_dir: ../data/Arrhythmia/arrhythmia.mat


