model:
  class_path: pyad.lightning.one_class.LitDeepSVDD
  init_args:
    feature_dim: 128
    hidden_dims:
      - 32
      - 64
    activation: relu
    eps: 0.1
    weight_decay: 1e-4
    lr: 1e-4